"""Response table added

Revision ID: 1becad5d7efa
Revises: f4ad433aa48e
Create Date: 2019-11-13 01:35:08.417581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1becad5d7efa'
down_revision = 'f4ad433aa48e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
