"""Added Foreign Keys

Revision ID: 5817f050db56
Revises: ebdc57616345
Create Date: 2019-11-12 18:52:35.872342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5817f050db56'
down_revision = 'ebdc57616345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'poll', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'poll', type_='foreignkey')
    # ### end Alembic commands ###
