"""Response table added

Revision ID: f4ad433aa48e
Revises: 82cdb081c895
Create Date: 2019-11-13 01:34:15.448268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ad433aa48e'
down_revision = '82cdb081c895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
