"""Added poll table

Revision ID: ec7ab4b48180
Revises: 7e48b8aa73b0
Create Date: 2019-11-11 18:04:24.741099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7ab4b48180'
down_revision = '7e48b8aa73b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=200), nullable=True),
    sa.Column('form_type', sa.Enum('multChoice', 'selectAll', 'numScale', 'freeResp', name='form_type'), nullable=True),
    sa.Column('resp_struct', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll')
    # ### end Alembic commands ###
