"""Response table added

Revision ID: 82cdb081c895
Revises: 56dff23df14a
Create Date: 2019-11-13 01:31:06.192692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82cdb081c895'
down_revision = '56dff23df14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('responder_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.ForeignKeyConstraint(['responder_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('responses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('poll_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('responder_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], name='responses_poll_id_fkey'),
    sa.ForeignKeyConstraint(['responder_id'], ['user.id'], name='responses_responder_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='responses_pkey')
    )
    op.drop_table('response')
    # ### end Alembic commands ###
