export const POLL_CREATION_FAILURE = 'POLL_CREATION_FAILURE'
export const POLL_CREATION_SUCCESS = 'POLL_CREATION_SUCCESS'

export const GET_POLLS_SUBSCRIBED_TO_SUCCESS = 'GET_POLLS_SUBSCRIBED_TO_SUCCESS'
export const GET_POLLS_SUBSCRIBED_TO_FAILURE = 'GET_POLLS_SUBSCRIBED_TO_FAILURE'
