export const POLL_CREATION_FAILURE = 'POLL_CREATION_FAILURE'
export const POLL_CREATION_SUCCESS = 'POLL_CREATION_SUCCESS'

export const GET_POLLS_SUBSCRIBED_TO_SUCCESS = 'GET_POLLS_SUBSCRIBED_TO_SUCCESS'
export const GET_POLLS_SUBSCRIBED_TO_FAILURE = 'GET_POLLS_SUBSCRIBED_TO_FAILURE'

export const ANSWER_POLL_SUCCESS = 'ANSWER_POLL_SUCCESS'
export const ANSWER_POLL_FAILURE = 'ANSWER_POLL_FAILURE'

export const CHECK_RESPONDED_TO_POLL_SUCCESS = 'CHECK_RESPONDED_TO_POLL_SUCCESS'
export const CHECK_RESPONDED_TO_POLL_FAILURE = 'CHECK_RESPONDED_TO_POLL_FAILURE'

export const GET_MY_POLLS_SUCCESS = 'GET_MY_POLLS_SUCCESS'
export const GET_MY_POLLS_FAILURE = 'GET_MY_POLLS_FAILURE'

export const GET_POLL_RESPONSE_SUCCESS = 'GET_POLL_RESPONSE_SUCCESS'
export const GET_POLL_RESPONSE_FAILURE = 'GET_POLL_RESPONSE_FAILURE'

