// @flow

export const CREATE_INVITE_REQUEST_SUCCESS = 'CREATE_INVITE_REQUEST_SUCCESS'
export const CREATE_INVITE_REQUEST_FAILURE = 'CREATE_INVITE_REQUEST_FAILURE'

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const GET_SUBSCRIBERS_SUCCESS = 'GET_SUBSCRIBERS_SUCCESS'
export const GET_SUBSCRIBERS_FAILURE = 'GET_SUBSCRIBERS_FAILURE'
export const GET_SUBSCRIBEDTO_SUCCESS = 'GET_SUBSCRIBEDTO_SUCCESS'
export const GET_SUBSCRIBEDTO_FAILURE = 'GET_SUBSCRIBEDTO_FAILURE'


export const GET_ME_SUCCESS = 'GET_ME_SUCCESS'
export const GET_ME_FAILURE = 'GET_ME_FAILURE'
