// @flow

export const CREATE_INVITE_REQUEST_SUCCESS = 'CREATE_INVITE_REQUEST_SUCCESS'
export const CREATE_INVITE_REQUEST_FAILURE = 'CREATE_INVITE_REQUEST_FAILURE'

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'
