"""remove follower table

Revision ID: 476f177f4ba0
Revises: ba822cf4397b
Create Date: 2019-11-25 08:18:20.253060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '476f177f4ba0'
down_revision = 'ba822cf4397b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relationship_status', postgresql.ENUM('pending', 'accepted', name='relationship_status'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='followers_follower_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='followers_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'follower_id', name='followers_pkey')
    )
    # ### end Alembic commands ###
