"""add fb fields to user model

Revision ID: 5099a4828b6b
Revises: 19d4bbe27656
Create Date: 2019-11-24 01:59:40.031532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5099a4828b6b'
down_revision = '19d4bbe27656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fb_id', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('user', 'fb_id')
    # ### end Alembic commands ###
